### ISSUE TITLE
Letras faltando?

### ISSUE THREAD

**Issue by parjanya** [aniseferreira/Grc-Por-DigDict#1]
Olá!

Obrigado por esse trabalho imenso!

Eu estou fazendo testes com os arquivos, talvez eu faça outra interface para o dicionário, com todos os créditos &c, mas parece que faltam os arquivos da letra epsilon (devia ser o arquivo `05_*`) e da letra upsilon (`20_*`). Eles existem, estão disponíveis nalgum lugar?

Eu tenho várias coisas a perguntar, como sobre uns caracteres especiais espalhados pelas entradas, mas este é um começo :). Obrigado de novo!

**Comment by aniseferreira** [comment]
Os arquivos faltando foram incluídos. Sobre caracteres especiais espalhados pelas entradas, não entendi exatamente a que v. se refere. Seria bom colar um exemplo na sua msg.  Obrigada por avisar.
